application: decoded-badge-656
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /components
  static_dir: bower_components

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
